// import React , { useState } from "react";
// import { Suggestion, ISelectedItem, SelectedItem } from "@essnextgen/ui-kit";
// import { useLocation } from "react-router-dom";
// import {
//   BreadcrumbAction,
//   DateRange,
//   DocumentData,
//   SelectedDocument,
//   SidePanelReason,
//   ViewDownloadItem
// } from "./responseModel";
// import { breadcrumbActionsList } from "./DocumentManagementServer.utils";

// export const useDocumentManagementState = (t: any) => {
  

//   return {
//     location,
//      dialogType, setDialogType,
//     currentPage, setCurrentPage,
//     totalPage, setTotalPage,
//     searchInput, setSearchInput,
//     searchTerm, setSearchTerm,
//     searchText, setSearchText,
//     suggestions, setSuggestions,
//     isSearchLoading, setIsSearchLoading,
//     isSearchTriggered, setIsSearchTriggered,
//     showSearchError, setShowSearchError,
//     docData, setDocData,
//     issearchDataLoading, setIsSearchDataLoading,
//     showErrorBanner, setShowErrorBanner,
//     sortBy, setSortBy,
//     sortDirection, setSortDirection,
//     visibleBreadcrumbs,
//     dateRange, setDateRange,
//     selectedDateRange, setSelectedDateRange,
//     isDateError, setIsDateError,
//     selectedCategories, setSelectedCategories,
//     selectedFormats, setSelectedFormats,
//     allSelectedDocs, setAllSelectedDocs,
//     selectedEntities, setSelectedEntities,
//     tagListArray, setTagListArray,
//     viewData, setViewData,
//     downloadPollingIntervalRef,
//     isFilterDialogOpen, setIsFilterDialogOpen,
//     isFilterLoading, setIsFilterLoading,
//     isClearSelectedCheckbox, setIsClearSelectedCheckbox,
//     isSidePanelOpen, setIsSidePanelOpen,
//     sidePanelOpenReason, setSidePanelOpenReason,
//     isSidePanelLoader, setIsSidePanelLoader,
//     showDialog, setShowDialog,
//     showConfirmDialog, setShowConfirmDialog,
//     selectedCheckBoxIds, setSelectedCheckBoxIds,
//     excludedCheckBoxIds, setExcludedCheckBoxIds,
//     // prevSelectedDocs, setPrevSelectedDocs,
//     isHeaderBoxChecked, setIsHeaderBoxChecked,
//     documentRelatedTo, setDocumentRelatedTo,
//     searchRefExternalId, setSearchRefExternalId,
//     showDeleteSuccessToast, setShowDeleteSuccessToast,
//     showDeleteAbortBanner, setShowDeleteAbortBanner,
//     restrictedFileCount, setRestrictedFileCount,
//     alreadyDeletedFileCount, setAlreadyDeletedFileCount,
//     availableFileCount, setAvailableFileCount,
//     availableFileIds, setAvailableFileIds,
//     showRestrictedDeleteDialog, setShowRestrictedDeleteDialog,
//     showRestrictedPrepareDialog, setShowRestrictedPrepareDialog,
//     isPreDialogLoading, setIsPreDialogLoading,
//     isDialogLoading, setIsDialogLoading,
//     isInitialLoad, setIsInitialLoad,
//     tableKey, setTableKey,
//     totalSelectedCount, setTotalSelectedCount,
//     isGlobalLoaderModel, setIsGlobalLoaderModel,
//     // prepareDownloadError, setPrepareDownloadError,
//     // PrepareDownloadAbortBanner, setPrepareDownloadAbortBanner,
//     // clearAllError, setClearAllError,
//     // showEmailNotification, setShowEmailNotification,
//     // showToastNotification, setShowToastNotification,
//     // downloadError, setDownloadError,
//     // failedFileName, setFailedFileName,
//     // hasFetchedViewDownload, setHasFetchedViewDownload,
//     // isViewDownloadError, setIsViewDownloadError,
//     selectedRelatedTo, setSelectedRelatedTo,
//     showDeleteErrorBanner, setShowDeleteErrorBanner ,
//     setPrepareDownloadError,
//     setPrepareDownloadAbortBanner,
//     setClearAllError,
//     setShowEmailNotification,
//     setShowToastNotification,
//     setFailedFileName,
//     setHasFetchedViewDownload,
//     setIsViewDownloadError,
//     setPrevSelectedDocs,
    
//   };
// };
