import { render, queryByAttribute, act,screen } from "@testing-library/react";
import NoAccess from "../index";

jest.mock("@essnextgen/auth-ui", () => ({
  authService: {
    getAuthTokens: jest.fn(),
  },
}));

describe("No Access page", () => {
  const getById: any = queryByAttribute.bind(null, "id");

  test("should render the component", () => {
    const renderResult = render(<NoAccess />);
    const container: any = getById(renderResult.container, "no-access-page");

    expect(container).toBeInTheDocument();
  });

  test("renders NoAccessView with isAuthzAdmin set to true when user is an admin", async () => {
    // eslint-disable-next-line global-require
    require("@essnextgen/auth-ui").authService.getAuthTokens.mockReturnValue("eyJhbGciOiJSUzI1NiIsImtpZCI6IkFBNDhENDA2QThCNDVFOUYyQTY4RjZGM0M2MzgwM0Y5N0M0NzU4NDFSUzI1NiIsIng1dCI6InFralVCcWkwWHA4cWFQYnp4amdELVh4SFdFRSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2NvcmUtZGV2LnNpbXMuY28udWsiLCJuYmYiOjE3MDI1NTgzNDksImlhdCI6MTcwMjU1ODM0OSwiZXhwIjoxNzAyNTYxOTQ5LCJhdWQiOlsib2RhdGFhcGkiLCJodHRwczovL2NvcmUtZGV2LnNpbXMuY28udWsvcmVzb3VyY2VzIl0sInNjb3BlIjpbIkFjdGl2ZUNsaWVudCIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJjdXN0b20iXSwiY2xpZW50X2lkIjoiSW50ZXJuYWxBY3RpdmVDbGllbnQiLCJzdWIiOiIxNDI3Nzh8MTVBRkQ2RDMtM0UxMS00M0UzLThCMkUtMkFBRjE4NkJBRDMxfEluaXRpYWwuQWRtaW42NjNAaWRlbnRpdHlmb3Iuc2ltc2lkLnBsYWNlaG9sZGVyLmNvLnVrfFNJTVMgSUR8NmJjYjQ0ZDctMzBiYS00ODUxLWEwODktODJmZjU3YTc2MGEzIiwiYXV0aF90aW1lIjoxNzAyNTU4MzQ5LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiIxNDI3Nzh8MTVBRkQ2RDMtM0UxMS00M0UzLThCMkUtMkFBRjE4NkJBRDMxfEluaXRpYWwuQWRtaW42NjNAaWRlbnRpdHlmb3Iuc2ltc2lkLnBsYWNlaG9sZGVyLmNvLnVrfFNJTVMgSUR8NmJjYjQ0ZDctMzBiYS00ODUxLWEwODktODJmZjU3YTc2MGEzIiwiU0lNU0lEL2lzc3Vlcm5hbWUiOiJFbnRlcnByaXNlIiwidmVuZG9yaWQiOiIyODYxQTAwMC03OTM0LTQ0QkYtOUY2RS05NkE5MjIyNjZGMzkiLCJhcHBsaWNhdGlvbmlkIjoiQ0E5MUMwMjEtRjA0RC00RkU1LUE0NUMtRTFCQTlCRUVFNDFBIiwiYXBwbGljYXRpb25uYW1lIjoiRVNTLVNhdGVsbGl0ZXMtRGV2ZWxvcG1lbnQtU0lNUyBOZXh0IEdlbiIsIlNJTVNDWC9VU0QiOiJUcnVlIiwiU0lNU0NYL0RvbWFpbiI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsIlNJTVNDWC9SZWdpb25JZGVudGlmaWVyIjoiIiwiU0lNU0NYL1ZhcmlhbnRDb2RlIjoiIiwiU0lNU0NYL0ludGVudHMiOiIiLCJTSU1TQ1gvT3JnYW5pc2F0aW9uSUQiOiJhNDc5Y2MxNy0xMWQzLTQyYzctOTUzMS1jZmEyOWY4OGUyYjgiLCJTSU1TQ1gvUm9sZSI6ImFkbWluQGE0NzljYzE3LTExZDMtNDJjNy05NTMxLWNmYTI5Zjg4ZTJiOCIsIlNJTVNDWC9FeHRlcm5hbElEIjoiMWEyZGRkZWMtODNmNS00N2QwLWI4OWEtNDY4NWY4OGUxY2Y3IiwiU0lNU0NYL1RlbmFudElEIjoiMzk3IiwianRpIjoiRTY0QUYxQzdCRTk2MzEzN0U0RDBDNzRCOEQ5NzYzRDIifQ.lz8hC15mKB0Tu77B3BO08xk2W6Vo-t4tpUZjQnRFZgesHE5OKTgjkYMq5VAsreRzN_oX9vDEp4tznVV1pBnj826z9I_DH7DzKHMWIGe9P-m9-EDUnEYDI4hrN2V66iqnovccT0ehSPTrNJIRRfkyGsgz-XLdE4nKPIYjDOk3oN0mAdtY2C-srEbR4AlffTogEvLTkfToZjcYamFnXp7qV-6m4T1d4LyF_4r7tV55wfgt5IJr9-ZXETnWeuPuazNz-pS6ENQ-5AcDZbo08yw_bOihlcc8VMelG2enRruS7S1K2_0LVQWzpSQvbCeCeLwptkYnwQ9MdUk9DuRSxZrCLqJ2lIhHCl4ia5qBXDK_Stzlgc58luyPkjWj9zA5qAxp4mu4uz7Zz0gC0eqvomxW7Z54663Y0sOuj3kZCacqUidjtGC7_7BXQIfmlJC4A_j6Kx80XLKwG2tic93rcma6DsYQ1dzJRmuNyl7IgpnfUonRbxyVv9tCtCDEEEwYCVLfOZHmn5-GRaORrfd8UdzX5a7DPUPNF-RqpqYydtBv6l6QqHSl6PhFoB2SCffba5tP4A60McDaNlIc8pLLvnkV-AxtS8xbJQW1KHpcRG97rJBntPqE_Bs3UWcRwV7TLwTIVa2J_ZXL6MPvjPEzzWc1YAQ16-PUWq6tg2BGIAwPu5k");

    jest.mock("jwt-decode", () => () => ({ "SIMSCX/Role": "admin@someotherdata" }));

    await act(async () => {
      render(<NoAccess />);
    });
    expect(screen.getByTestId('no-access-admin')).toBeInTheDocument();
  });

  test("renders NoAccessView with isAuthzAdmin set to false when user is not an admin", async () => {
    // eslint-disable-next-line global-require
    require("@essnextgen/auth-ui").authService.getAuthTokens.mockReturnValue("eyJhbGciOiJSUzI1NiIsImtpZCI6IkFBNDhENDA2QThCNDVFOUYyQTY4RjZGM0M2MzgwM0Y5N0M0NzU4NDFSUzI1NiIsIng1dCI6InFralVCcWkwWHA4cWFQYnp4amdELVh4SFdFRSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2NvcmUtZGV2LnNpbXMuY28udWsiLCJuYmYiOjE3MDI1NTkwMjcsImlhdCI6MTcwMjU1OTAyNywiZXhwIjoxNzAyNTYyNjI3LCJhdWQiOlsib2RhdGFhcGkiLCJodHRwczovL2NvcmUtZGV2LnNpbXMuY28udWsvcmVzb3VyY2VzIl0sInNjb3BlIjpbIkFjdGl2ZUNsaWVudCIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJjdXN0b20iXSwiY2xpZW50X2lkIjoiSW50ZXJuYWxBY3RpdmVDbGllbnQiLCJzdWIiOiIxNTU0MjB8NDYxRUMwOEYtMDNBRi00NkZCLTlBNDgtQ0Y4QzM0NzU4NDcyfEFsYmVydFNpbW1vbnNEZXZTM0BleGFtcGxlLmNvbXxTSU1TIElEfDlhYzE4YzdkLTZmNTAtNDc4Ny1iNTYzLTQzN2QyYWMzZmUxNSIsImF1dGhfdGltZSI6MTcwMjU1OTAyNywiaWRwIjoibG9jYWwiLCJuYW1lIjoiMTU1NDIwfDQ2MUVDMDhGLTAzQUYtNDZGQi05QTQ4LUNGOEMzNDc1ODQ3MnxBbGJlcnRTaW1tb25zRGV2UzNAZXhhbXBsZS5jb218U0lNUyBJRHw5YWMxOGM3ZC02ZjUwLTQ3ODctYjU2My00MzdkMmFjM2ZlMTUiLCJTSU1TSUQvaXNzdWVybmFtZSI6IkVudGVycHJpc2UiLCJ2ZW5kb3JpZCI6IjI4NjFBMDAwLTc5MzQtNDRCRi05RjZFLTk2QTkyMjI2NkYzOSIsImFwcGxpY2F0aW9uaWQiOiJDQTkxQzAyMS1GMDRELTRGRTUtQTQ1Qy1FMUJBOUJFRUU0MUEiLCJhcHBsaWNhdGlvbm5hbWUiOiJFU1MtU2F0ZWxsaXRlcy1EZXZlbG9wbWVudC1TSU1TIE5leHQgR2VuIiwiU0lNU0NYL1VTRCI6IlRydWUiLCJTSU1TQ1gvRG9tYWluIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwiU0lNU0NYL1JlZ2lvbklkZW50aWZpZXIiOiIiLCJTSU1TQ1gvVmFyaWFudENvZGUiOiIiLCJTSU1TQ1gvSW50ZW50cyI6IiIsIlNJTVNDWC9PcmdhbmlzYXRpb25JRCI6IjQzMGMwZWRjLTY0ODItNDc2ZC1hZTE4LTJlYWMyM2U1NzYyMSIsIlNJTVNDWC9Sb2xlIjoidXNlckA0MzBjMGVkYy02NDgyLTQ3NmQtYWUxOC0yZWFjMjNlNTc2MjEiLCJTSU1TQ1gvVGVuYW50SUQiOiI5ODEiLCJTSU1TQ1gvRXh0ZXJuYWxJRCI6ImZhZDJkNWY4LWQyNDAtNDQxZS1hMTc3LWM5ZTZhY2U5ZDY3NCIsIlNJTVNDWC9Vc2VyVHlwZSI6IlN0YWZmIiwiU0lNU0NYL1ZpZXc2IjoiOTIxOTk2ODAzNDIwMDg3OTEwNCIsIlNJTVNDWC9DcmVhdGU2IjoiNjMzMzIwODc4NjM3MDU2IiwiU0lNU0NYL0RlbGV0ZTYiOiI2MzMzMjA4NDUwODI2MjQiLCJTSU1TQ1gvV3JpdGU2IjoiNjMzMzIxOTUyMzc4ODgwIiwiU0lNU0NYL1VwZGF0ZTYiOiI2MzMzMjE5NTIzNzg4ODAiLCJTSU1TQ1gvQ3JlYXRlNCI6IjI2ODQzODczMjgiLCJTSU1TQ1gvVmlldzciOiIxMDcyNzExMDI5NzUxODA4IiwiU0lNU0NYL1ZpZXc1IjoiOTIyMTAxMDI4NTg3ODMxMjk2MCIsIlNJTVNDWC9DcmVhdGU1IjoiNDk2ODQ3MzE0MzU5NDE4ODgiLCJTSU1TQ1gvRGVsZXRlNSI6IjQ5NjgwMzMzMzg5NDMwNzg0IiwiU0lNU0NYL1dyaXRlNSI6IjQ5NjgwMzMzMzg5NDMwNzg0IiwiU0lNU0NYL1VwZGF0ZTUiOiI0OTY4MDMzMzM4OTQzMDc4NCIsIlNJTVNDWC9DcmVhdGU3IjoiNTYzMDA1NzgzODAxODU2IiwiU0lNU0NYL0RlbGV0ZTciOiI1NTgzMDM4MDU0NCIsIlNJTVNDWC9Xcml0ZTciOiI1NjMwMDU3ODM4MDE4NTYiLCJTSU1TQ1gvVXBkYXRlNyI6IjU2MzAwNTc4MzgwMTg1NiIsIlNJTVNDWC9WaWV3MSI6IjQzOTgwNDY2NTAzOTAiLCJTSU1TQ1gvRGVsZXRlNCI6IjI2ODQ2MTY3MDQiLCJTSU1TQ1gvV3JpdGU0IjoiMjY4NDM1NDU2MCIsIlNJTVNDWC9VcGRhdGU0IjoiMjY4NDM1NDU2MCIsIlNJTVNDWC9WaWV3NCI6IjQwMjY1MzE4NDIiLCJTSU1TQ1gvVmlldzIiOiI4Mzg4NjA4IiwianRpIjoiNjk1RkNFMjhCNzJENTAwRTYxQzQ4MUQ5QTJDQkZCOUUifQ.np1DAjBd3mpFQhU1aKs35ZKy4bALFyN1BthZx1gpXFZiBxqdPbECNYhll5hP9GG0qjk5Ue97PVwb6bWR66MzxoEp_hyt1pfanlmTcxiWupbWMoGf7M8iUjwf06-6NMYeDVH3GEYuwrHFFL6H7H6cWuCdsh08Cemh6MzmDgeUM-2RyiFnSPth9lmZ8NgyM_-ezVLmTgu0Yzb_gBCu0cdf-X5W8JDiIHYJOAejjA0dhYcQEbGKdfriXYmcYS0wn_s6ofKDM8_-PZGWV2pn5VHuEOFo5EmiElYHQrtglmuNP1QkXESieVdAhBMZIMCkWOOjNbSJkbykXC0Om7qRLwvlltmZXFVEJ-iajnXdmoLhfjhn2ePLFQLuwfT09_YN196W-JGEg8IPQUqsMhoj6fpFl3EeTO8Rk1rgmEZQUZ5Az6fo6gK0ptTLJcO1pxhvR00wlsRpAX4hjxHpUNbFFinVxkVKoD7ch9sE6w1GN8IkUlzwAZlmNHvOApogsJQUUysS5ZlfYsiXgHeZcb7FBAabCB2CwdV4dkznjwkytBbTYvqbdZcXtq7z8BrDcdWwZlxPPwFirEBTLUpAeft5OuzBQDEHgvVhggTRUT4jDrlgqf_UvUYuxxXblnjlIO2tiKDqgBBJkNX6Hs29LESt--dS8q8ggq7-S0ujEkLNhcG3bQg");

    jest.mock("jwt-decode", () => () => ({ "SIMSCX/Role": "user@someotherdata" }));

    await act(async () => {
      render(<NoAccess />);
    });
    expect(screen.getByTestId('no-access-non-admin')).toBeInTheDocument();
  });

  test("renders NoAccessView with isAuthzAdmin set to false when there is no access token", async () => {
    // eslint-disable-next-line global-require
    require("@essnextgen/auth-ui").authService.getAuthTokens.mockReturnValue(null);

    await act(async () => {
      render(<NoAccess />);
    });

    expect(screen.getByTestId('no-access-non-admin')).toBeInTheDocument();
  });

  
  test('renders NoAccessView with IsAuthzAdmin set to false when decodedToken is undefined or null', () => {
    // eslint-disable-next-line global-require
    require("@essnextgen/auth-ui").authService.getAuthTokens.mockReturnValue(undefined);

    act(async () => {
      render(<NoAccess />);
    });

    expect(screen.getByTestId('no-access-non-admin')).toBeInTheDocument();
  });


  test("renders NoAccessView with isAuthzAdmin set to false when role is not present or undefined", async () => {
    // eslint-disable-next-line global-require
    require("@essnextgen/auth-ui").authService.getAuthTokens.mockReturnValue("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2NvcmUtZGV2LnNpbXMuY28udWsiLCJuYmYiOjE3MDI1NTgzNDksImlhdCI6MTcwMjU1ODM0OSwiZXhwIjoxNzAyNTYxOTQ5LCJhdWQiOlsib2RhdGFhcGkiLCJodHRwczovL2NvcmUtZGV2LnNpbXMuY28udWsvcmVzb3VyY2VzIl0sInNjb3BlIjpbIkFjdGl2ZUNsaWVudCIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJjdXN0b20iXSwiY2xpZW50X2lkIjoiSW50ZXJuYWxBY3RpdmVDbGllbnQiLCJzdWIiOiIxNDI3Nzh8MTVBRkQ2RDMtM0UxMS00M0UzLThCMkUtMkFBRjE4NkJBRDMxfEluaXRpYWwuQWRtaW42NjNAaWRlbnRpdHlmb3Iuc2ltc2lkLnBsYWNlaG9sZGVyLmNvLnVrfFNJTVMgSUR8NmJjYjQ0ZDctMzBiYS00ODUxLWEwODktODJmZjU3YTc2MGEzIiwiYXV0aF90aW1lIjoxNzAyNTU4MzQ5LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiIxNDI3Nzh8MTVBRkQ2RDMtM0UxMS00M0UzLThCMkUtMkFBRjE4NkJBRDMxfEluaXRpYWwuQWRtaW42NjNAaWRlbnRpdHlmb3Iuc2ltc2lkLnBsYWNlaG9sZGVyLmNvLnVrfFNJTVMgSUR8NmJjYjQ0ZDctMzBiYS00ODUxLWEwODktODJmZjU3YTc2MGEzIiwiU0lNU0lEL2lzc3Vlcm5hbWUiOiJFbnRlcnByaXNlIiwidmVuZG9yaWQiOiIyODYxQTAwMC03OTM0LTQ0QkYtOUY2RS05NkE5MjIyNjZGMzkiLCJhcHBsaWNhdGlvbmlkIjoiQ0E5MUMwMjEtRjA0RC00RkU1LUE0NUMtRTFCQTlCRUVFNDFBIiwiYXBwbGljYXRpb25uYW1lIjoiRVNTLVNhdGVsbGl0ZXMtRGV2ZWxvcG1lbnQtU0lNUyBOZXh0IEdlbiIsIlNJTVNDWC9VU0QiOiJUcnVlIiwiU0lNU0NYL0RvbWFpbiI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsIlNJTVNDWC9SZWdpb25JZGVudGlmaWVyIjoiIiwiU0lNU0NYL1ZhcmlhbnRDb2RlIjoiIiwiU0lNU0NYL0ludGVudHMiOiIiLCJTSU1TQ1gvT3JnYW5pc2F0aW9uSUQiOiJhNDc5Y2MxNy0xMWQzLTQyYzctOTUzMS1jZmEyOWY4OGUyYjgiLCJTSU1TQ1gvRXh0ZXJuYWxJRCI6IjFhMmRkZGVjLTgzZjUtNDdkMC1iODlhLTQ2ODVmODhlMWNmNyIsIlNJTVNDWC9UZW5hbnRJRCI6IjM5NyIsImp0aSI6IkU2NEFGMUM3QkU5NjMxMzdFNEQwQzc0QjhEOTc2M0QyIn0.RKkzC28f8LkeJP-AwaYvCIgPWbL_x9ar_pacgkMekds");

//    jest.mock("jwt-decode", () => () => (""));

    await act(async () => {
      render(<NoAccess />);
    });
    expect(screen.getByTestId('no-access-non-admin')).toBeInTheDocument();
  });

  test("renders NoAccessView with isAuthzAdmin set to false when role is not present or null", async () => {
    // eslint-disable-next-line global-require
    require("@essnextgen/auth-ui").authService.getAuthTokens.mockReturnValue("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2NvcmUtZGV2LnNpbXMuY28udWsiLCJuYmYiOjE3MDI1NTgzNDksImlhdCI6MTcwMjU1ODM0OSwiZXhwIjoxNzAyNTYxOTQ5LCJhdWQiOlsib2RhdGFhcGkiLCJodHRwczovL2NvcmUtZGV2LnNpbXMuY28udWsvcmVzb3VyY2VzIl0sInNjb3BlIjpbIkFjdGl2ZUNsaWVudCIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJjdXN0b20iXSwiY2xpZW50X2lkIjoiSW50ZXJuYWxBY3RpdmVDbGllbnQiLCJzdWIiOiIxNDI3Nzh8MTVBRkQ2RDMtM0UxMS00M0UzLThCMkUtMkFBRjE4NkJBRDMxfEluaXRpYWwuQWRtaW42NjNAaWRlbnRpdHlmb3Iuc2ltc2lkLnBsYWNlaG9sZGVyLmNvLnVrfFNJTVMgSUR8NmJjYjQ0ZDctMzBiYS00ODUxLWEwODktODJmZjU3YTc2MGEzIiwiYXV0aF90aW1lIjoxNzAyNTU4MzQ5LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiIxNDI3Nzh8MTVBRkQ2RDMtM0UxMS00M0UzLThCMkUtMkFBRjE4NkJBRDMxfEluaXRpYWwuQWRtaW42NjNAaWRlbnRpdHlmb3Iuc2ltc2lkLnBsYWNlaG9sZGVyLmNvLnVrfFNJTVMgSUR8NmJjYjQ0ZDctMzBiYS00ODUxLWEwODktODJmZjU3YTc2MGEzIiwiU0lNU0lEL2lzc3Vlcm5hbWUiOiJFbnRlcnByaXNlIiwidmVuZG9yaWQiOiIyODYxQTAwMC03OTM0LTQ0QkYtOUY2RS05NkE5MjIyNjZGMzkiLCJhcHBsaWNhdGlvbmlkIjoiQ0E5MUMwMjEtRjA0RC00RkU1LUE0NUMtRTFCQTlCRUVFNDFBIiwiYXBwbGljYXRpb25uYW1lIjoiRVNTLVNhdGVsbGl0ZXMtRGV2ZWxvcG1lbnQtU0lNUyBOZXh0IEdlbiIsIlNJTVNDWC9VU0QiOiJUcnVlIiwiU0lNU0NYL0RvbWFpbiI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsIlNJTVNDWC9SZWdpb25JZGVudGlmaWVyIjoiIiwiU0lNU0NYL1ZhcmlhbnRDb2RlIjoiIiwiU0lNU0NYL0ludGVudHMiOiIiLCJTSU1TQ1gvT3JnYW5pc2F0aW9uSUQiOiJhNDc5Y2MxNy0xMWQzLTQyYzctOTUzMS1jZmEyOWY4OGUyYjgiLCJTSU1TQ1gvRXh0ZXJuYWxJRCI6IjFhMmRkZGVjLTgzZjUtNDdkMC1iODlhLTQ2ODVmODhlMWNmNyIsIlNJTVNDWC9UZW5hbnRJRCI6IjM5NyIsImp0aSI6IkU2NEFGMUM3QkU5NjMxMzdFNEQwQzc0QjhEOTc2M0QyIn0.RKkzC28f8LkeJP-AwaYvCIgPWbL_x9ar_pacgkMekds");

  //  jest.mock("jwt-decode", () => () => (""));

    await act(async () => {
      render(<NoAccess />);
    });
    expect(screen.getByTestId('no-access-non-admin')).toBeInTheDocument();
  });

  test("renders NoAccessView with isAuthzAdmin set to false when role is without ampersand", async () => {
    // eslint-disable-next-line global-require
    require("@essnextgen/auth-ui").authService.getAuthTokens.mockReturnValue("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2NvcmUtZGV2LnNpbXMuY28udWsiLCJuYmYiOjE3MDI1NTgzNDksImlhdCI6MTcwMjU1ODM0OSwiZXhwIjoxNzAyNTYxOTQ5LCJhdWQiOlsib2RhdGFhcGkiLCJodHRwczovL2NvcmUtZGV2LnNpbXMuY28udWsvcmVzb3VyY2VzIl0sInNjb3BlIjpbIkFjdGl2ZUNsaWVudCIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJjdXN0b20iXSwiY2xpZW50X2lkIjoiSW50ZXJuYWxBY3RpdmVDbGllbnQiLCJzdWIiOiIxNDI3Nzh8MTVBRkQ2RDMtM0UxMS00M0UzLThCMkUtMkFBRjE4NkJBRDMxfEluaXRpYWwuQWRtaW42NjNAaWRlbnRpdHlmb3Iuc2ltc2lkLnBsYWNlaG9sZGVyLmNvLnVrfFNJTVMgSUR8NmJjYjQ0ZDctMzBiYS00ODUxLWEwODktODJmZjU3YTc2MGEzIiwiYXV0aF90aW1lIjoxNzAyNTU4MzQ5LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiIxNDI3Nzh8MTVBRkQ2RDMtM0UxMS00M0UzLThCMkUtMkFBRjE4NkJBRDMxfEluaXRpYWwuQWRtaW42NjNAaWRlbnRpdHlmb3Iuc2ltc2lkLnBsYWNlaG9sZGVyLmNvLnVrfFNJTVMgSUR8NmJjYjQ0ZDctMzBiYS00ODUxLWEwODktODJmZjU3YTc2MGEzIiwiU0lNU0lEL2lzc3Vlcm5hbWUiOiJFbnRlcnByaXNlIiwidmVuZG9yaWQiOiIyODYxQTAwMC03OTM0LTQ0QkYtOUY2RS05NkE5MjIyNjZGMzkiLCJhcHBsaWNhdGlvbmlkIjoiQ0E5MUMwMjEtRjA0RC00RkU1LUE0NUMtRTFCQTlCRUVFNDFBIiwiYXBwbGljYXRpb25uYW1lIjoiRVNTLVNhdGVsbGl0ZXMtRGV2ZWxvcG1lbnQtU0lNUyBOZXh0IEdlbiIsIlNJTVNDWC9VU0QiOiJUcnVlIiwiU0lNU0NYL0RvbWFpbiI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsIlNJTVNDWC9SZWdpb25JZGVudGlmaWVyIjoiIiwiU0lNU0NYL1ZhcmlhbnRDb2RlIjoiIiwiU0lNU0NYL0ludGVudHMiOiIiLCJTSU1TQ1gvT3JnYW5pc2F0aW9uSUQiOiJhNDc5Y2MxNy0xMWQzLTQyYzctOTUzMS1jZmEyOWY4OGUyYjgiLCJTSU1TQ1gvUm9sZSI6ImFkbWluIiwiU0lNU0NYL0V4dGVybmFsSUQiOiIxYTJkZGRlYy04M2Y1LTQ3ZDAtYjg5YS00Njg1Zjg4ZTFjZjciLCJTSU1TQ1gvVGVuYW50SUQiOiIzOTciLCJqdGkiOiJFNjRBRjFDN0JFOTYzMTM3RTREMEM3NEI4RDk3NjNEMiJ9.5PAOl9YbGGsIScMnbaiI18ekGbJKStCUwJ4ZEtM92Fc");

    await act(async () => {
      render(<NoAccess />);
    });
    expect(screen.getByTestId('no-access-non-admin')).toBeInTheDocument();
  });

  test("renders NoAccessView with isAuthzAdmin set to false when role is null", async () => {
    // eslint-disable-next-line global-require
    require("@essnextgen/auth-ui").authService.getAuthTokens.mockReturnValue("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2NvcmUtZGV2LnNpbXMuY28udWsiLCJuYmYiOjE3MDI1NTgzNDksImlhdCI6MTcwMjU1ODM0OSwiZXhwIjoxNzAyNTYxOTQ5LCJhdWQiOlsib2RhdGFhcGkiLCJodHRwczovL2NvcmUtZGV2LnNpbXMuY28udWsvcmVzb3VyY2VzIl0sInNjb3BlIjpbIkFjdGl2ZUNsaWVudCIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJjdXN0b20iXSwiY2xpZW50X2lkIjoiSW50ZXJuYWxBY3RpdmVDbGllbnQiLCJzdWIiOiIxNDI3Nzh8MTVBRkQ2RDMtM0UxMS00M0UzLThCMkUtMkFBRjE4NkJBRDMxfEluaXRpYWwuQWRtaW42NjNAaWRlbnRpdHlmb3Iuc2ltc2lkLnBsYWNlaG9sZGVyLmNvLnVrfFNJTVMgSUR8NmJjYjQ0ZDctMzBiYS00ODUxLWEwODktODJmZjU3YTc2MGEzIiwiYXV0aF90aW1lIjoxNzAyNTU4MzQ5LCJpZHAiOiJsb2NhbCIsIm5hbWUiOiIxNDI3Nzh8MTVBRkQ2RDMtM0UxMS00M0UzLThCMkUtMkFBRjE4NkJBRDMxfEluaXRpYWwuQWRtaW42NjNAaWRlbnRpdHlmb3Iuc2ltc2lkLnBsYWNlaG9sZGVyLmNvLnVrfFNJTVMgSUR8NmJjYjQ0ZDctMzBiYS00ODUxLWEwODktODJmZjU3YTc2MGEzIiwiU0lNU0lEL2lzc3Vlcm5hbWUiOiJFbnRlcnByaXNlIiwidmVuZG9yaWQiOiIyODYxQTAwMC03OTM0LTQ0QkYtOUY2RS05NkE5MjIyNjZGMzkiLCJhcHBsaWNhdGlvbmlkIjoiQ0E5MUMwMjEtRjA0RC00RkU1LUE0NUMtRTFCQTlCRUVFNDFBIiwiYXBwbGljYXRpb25uYW1lIjoiRVNTLVNhdGVsbGl0ZXMtRGV2ZWxvcG1lbnQtU0lNUyBOZXh0IEdlbiIsIlNJTVNDWC9VU0QiOiJUcnVlIiwiU0lNU0NYL0RvbWFpbiI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsIlNJTVNDWC9SZWdpb25JZGVudGlmaWVyIjoiIiwiU0lNU0NYL1ZhcmlhbnRDb2RlIjoiIiwiU0lNU0NYL0ludGVudHMiOiIiLCJTSU1TQ1gvT3JnYW5pc2F0aW9uSUQiOiJhNDc5Y2MxNy0xMWQzLTQyYzctOTUzMS1jZmEyOWY4OGUyYjgiLCJTSU1TQ1gvUm9sZSI6bnVsbCwiU0lNU0NYL0V4dGVybmFsSUQiOiIxYTJkZGRlYy04M2Y1LTQ3ZDAtYjg5YS00Njg1Zjg4ZTFjZjciLCJTSU1TQ1gvVGVuYW50SUQiOiIzOTciLCJqdGkiOiJFNjRBRjFDN0JFOTYzMTM3RTREMEM3NEI4RDk3NjNEMiJ9.CfMzyJ_Z4Fpa482KksKJpebzq9Umg66fygaqr9ZidLw");

//    jest.mock("jwt-decode", () => () => (null));

    await act(async () => {
      render(<NoAccess />);
    });
    expect(screen.getByTestId('no-access-non-admin')).toBeInTheDocument();
  });
});
