export const SAVE_APP_MODULES = "SAVE_APP_MODULES";
export const REMOVE_APP_MODULES = "REMOVE_APP_MODULES";
export const APP_MODULES_FAILURE = "APP_MODULES_FAILURE";
export const APP_MODULES_REQUEST = "APP_MODULES_REQUEST";
export const VIDEO_PLAY_STATUS = "VIDEO_PLAY_STATUS";
export const VIDEO_API_ERROR = "VIDEO_API_ERROR";
