map $http_origin $allow_origin {
    ~^https?://(.*\.)?sims.co.uk(:\d+)?$ $http_origin;  
    default "";
}

server {
  listen 80;

  # Handle CORS
  location / {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' $allow_origin always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, HEAD';
            add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,Keep-Alive,Origin,request-id,Organisation-Id,traceparent';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            return 204;
        }
        
        add_header 'Access-Control-Allow-Origin' $allow_origin always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, HEAD';
        add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,Keep-Alive,Origin,request-id,Organisation-Id,traceparent';
        add_header Cache-Control "private, no-cache, no-store, must-revalidate";

        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Content Security Policy
    add_header Content-Security-Policy "
        default-src 'self';
        script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:;
        img-src 'self' https: data:;
        style-src 'self' 'unsafe-inline';
        connect-src 'self' https:;
        font-src 'self' https: data:;
    ";

    # MIME type fixes
    types {
        application/javascript js;
        text/css css;
    }
    
  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root  /usr/share/nginx/html;
  }  
}
